spring.application.name=express
#spring.datasource.url=jdbc:h2:mem:testdb
#spring.datasource.driverClassName=org.h2.Driver
#spring.datasource.username=sa
#spring.datasource.password=password
#spring.jpa.database-platform=org.hibernate.dialect.H2Dialect

spring.jpa.properties.hibernate.transaction.coordinator_class=org.hibernate.transaction.JDBCTransactionFactory
spring.jpa.properties.hibernate.transaction.jta.platform=null

spring.mail.host=smtp.gmail.com
spring.mail.port=587
spring.mail.username=pepelolaso64@gmail.com
spring.mail.password=tuddtqwgusmplvmz
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true
spring.mail.properties.mail.smtp.starttls.required=true
spring.mail.properties.mail.smtp.quitwait=false

spring.jpa.hibernate.ddl-auto=update
spring.datasource.url=jdbc:mysql://localhost:3306/viajesexpress
spring.datasource.username=root
spring.datasource.password=
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver
#spring.jpa.show-sql: true
spring.jpa.properties.hibernate.format_sql=true 